/* utils/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "4e40d6bd17e0fd5281b601104a432db9"

/* Revision testament checksum:
 * MD5:4e40d6bd17e0fd5281b601104a432db9
 */

/* Revision testament: */
#define USERNAME "Artur"
#define GECOS "U-ARTUR\\Artur"
#define WT_ROOT "/opt/netsurf/"
#define WT_HOSTNAME "artur"
#define WT_COMPILEDATE "13.01.2013"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "6975360e1c3aeeb8607857c5f9c11158a12b76ea"
#define WT_MODIFIED 42
#define WT_MODIFICATIONS {\
  { "!NetSurf/NetSurf.info", "??" }, \
  { "Makefile.sources.javascript", " M" }, \
  { "NetSurf.7z", "??" }, \
  { "NetSurf.info", "??" }, \
  { "amigaos3/", "??" }, \
  { "bash.bashrc", "??" }, \
  { "beos/NetSurf.info", "??" }, \
  { "bin/", "??" }, \
  { "data/", "??" }, \
  { "desktop/options.h", " M" }, \
  { "fonts/", "??" }, \
  { "framebuffer/gui.c", " M" }, \
  { "javascript/jsapi.c", " M" }, \
  { "nsgenbind.exe.stackdump", "??" }, \
  { "on", "??" }, \
  { "patch.txt", "??" }, \
  { "resources/AdBlock.css", "??" }, \
  { "resources/Aliases", "??" }, \
  { "resources/Aliases.info", "??" }, \
  { "resources/Messages", "??" }, \
  { "resources/Options", "??" }, \
  { "resources/Options.info", "??" }, \
  { "resources/URLhistory", "??" }, \
  { "resources/bookmarks.htm", "??" }, \
  { "resources/bookmarks.htm.info", "??" }, \
  { "resources/ca-bundle", "??" }, \
  { "resources/ca-bundle.info", "??" }, \
  { "resources/cookies", "??" }, \
  { "resources/credits.html", "??" }, \
  { "resources/default.css", "??" }, \
  { "resources/default.css.info", "??" }, \
  { "resources/icons.info", "??" }, \
  { "resources/icons/", "??" }, \
  { "resources/internal.css", "??" }, \
  { "resources/licence.html", "??" }, \
  { "resources/netsurf.png", "??" }, \
  { "resources/quirks.css", "??" }, \
  { "resources/quirks.css.info", "??" }, \
  { "resources/theme/", "??" }, \
  { "resources/welcome.html", "??" }, \
  { "share/", "??" }, \
  { "utils/utils.c", " M" } \
}

#endif
